language: java
env:
  global:
    - JAVA_OPTS="-Xmx512m"
dist: trusty
jdk:
  - oraclejdk8
before_install:
  - chmod -R ug+x .travis
  - if [ "$TRAVIS_REPO_SLUG" == "aperture-sh/charger" ]; then .travis/install.sh; fi
script:
  - ./gradlew check &&
    if [ "$TRAVIS_REPO_SLUG" == "aperture-sh/charger" ] && [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    ./gradlew upload;
    fi
# see also https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
